"""Synthetic data generation for the HCC grading demo.

No real patient data is used here. Every row is generated by code and exists
only to demonstrate the ML and Agent architecture.
"""

from __future__ import annotations

import math
from typing import Any

import numpy as np

from .features import CAUSAL_FEATURES, NON_CAUSAL_FEATURES


def _sigmoid(value: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-value))


def generate_synthetic_dataset(
    n_samples: int = 1200,
    random_state: int = 42,
) -> tuple[dict[str, np.ndarray], np.ndarray]:
    """Generate a synthetic binary grading dataset.

    Target meaning in this prototype:
    1 = synthetic high pathological grade
    0 = synthetic low/intermediate pathological grade
    """

    rng = np.random.default_rng(random_state)

    tumor_size_cm = np.clip(rng.gamma(shape=2.2, scale=2.1, size=n_samples) + 0.6, 0.5, 18.0)
    afp_ng_ml = np.clip(rng.lognormal(mean=5.6, sigma=1.25, size=n_samples), 0.5, 45000.0)
    alt_u_l = np.clip(rng.normal(loc=46, scale=22, size=n_samples), 5, 300)
    ast_u_l = np.clip(alt_u_l * rng.normal(loc=1.12, scale=0.22, size=n_samples), 5, 350)
    bilirubin_umol_l = np.clip(rng.gamma(shape=2.3, scale=7.5, size=n_samples), 2, 130)
    albumin_g_l = np.clip(rng.normal(loc=40.5, scale=4.5, size=n_samples), 18, 54)
    platelet_10e9_l = np.clip(rng.normal(loc=165, scale=55, size=n_samples), 25, 480)

    invasion_logit = -2.0 + 0.32 * (tumor_size_cm - 4.5) + 0.34 * (np.log1p(afp_ng_ml) - 5.3)
    portal_vein_invasion = rng.binomial(1, _sigmoid(invasion_logit))

    radiomics_entropy = np.clip(
        rng.normal(loc=4.55, scale=0.55, size=n_samples)
        + 0.07 * tumor_size_cm
        + 0.32 * portal_vein_invasion,
        2.0,
        8.0,
    )
    radiomics_glcm_contrast = np.clip(
        rng.normal(loc=78, scale=22, size=n_samples)
        + 4.0 * tumor_size_cm
        + 12.0 * portal_vein_invasion,
        10,
        240,
    )

    tumor_z = (tumor_size_cm - 5.0) / 2.6
    afp_z = (np.log1p(afp_ng_ml) - 5.5) / 1.4
    alt_z = (alt_u_l - 45.0) / 25.0
    ast_z = (ast_u_l - 50.0) / 25.0
    bilirubin_z = (bilirubin_umol_l - 18.0) / 8.0
    albumin_low = (40.0 - albumin_g_l) / 5.0
    platelet_low = (160.0 - platelet_10e9_l) / 55.0
    entropy_z = (radiomics_entropy - 4.8) / 0.7
    contrast_z = (radiomics_glcm_contrast - 88.0) / 28.0

    linear_risk = (
        -0.20
        + 0.78 * tumor_z
        + 0.62 * afp_z
        + 0.28 * alt_z
        + 0.32 * ast_z
        + 0.42 * bilirubin_z
        + 0.58 * albumin_low
        + 0.33 * platelet_low
        + 1.05 * portal_vein_invasion
        + 0.70 * entropy_z
        + 0.52 * contrast_z
        + rng.normal(loc=0.0, scale=0.72, size=n_samples)
    )
    high_grade = rng.binomial(1, _sigmoid(linear_risk))

    features: dict[str, np.ndarray] = {
        "tumor_size_cm": tumor_size_cm,
        "afp_ng_ml": afp_ng_ml,
        "alt_u_l": alt_u_l,
        "ast_u_l": ast_u_l,
        "bilirubin_umol_l": bilirubin_umol_l,
        "albumin_g_l": albumin_g_l,
        "platelet_10e9_l": platelet_10e9_l,
        "portal_vein_invasion": portal_vein_invasion.astype(float),
        "radiomics_entropy": radiomics_entropy,
        "radiomics_glcm_contrast": radiomics_glcm_contrast,
        "age_years": np.clip(rng.normal(loc=58, scale=10, size=n_samples), 25, 85),
        "sex_male": rng.binomial(1, 0.70, size=n_samples).astype(float),
        "hbv_marker": rng.binomial(1, 0.55, size=n_samples).astype(float),
        "synthetic_noise_1": rng.normal(loc=0, scale=1, size=n_samples),
        "synthetic_noise_2": rng.uniform(low=-1, high=1, size=n_samples),
        "scanner_protocol_id": rng.integers(low=1, high=4, size=n_samples).astype(float),
    }

    expected = set(CAUSAL_FEATURES + NON_CAUSAL_FEATURES)
    if set(features) != expected:
        raise RuntimeError("Synthetic feature generator does not match the feature contract.")

    return features, high_grade.astype(int)


def as_matrix(features: dict[str, np.ndarray], columns: list[str]) -> np.ndarray:
    return np.column_stack([features[name] for name in columns])


def sample_payload(random_state: int = 7) -> dict[str, Any]:
    features, _ = generate_synthetic_dataset(n_samples=1, random_state=random_state)
    return {name: float(features[name][0]) for name in CAUSAL_FEATURES}

